name: 测试环境
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on:
      - self-hosted
      - linux
      - x64
      - jp
    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: cmdb build
